### ISSUE TITLE
Installation guide problem

### ISSUE THREAD

**Issue by alu0101124896** [Paul-Houser/slickgreeter-pywal#3]
Hello,

Everything worked perfect for me but I figured out that you put `reTheme (cat $HOME/.cache/wal/wal)` at the installation guide when it should be `reTheme $(cat $HOME/.cache/wal/wal)`.

Just telling it to you to prevent any confusion on another less experimented user.

Regards.

**Comment by Paul-Houser** [comment]
Thank you! Fixed the readme.
